[[redirects]]
  from = "/lolCdnApi/*"
  to = "http://ddragon.leagueoflegends.com/cdn/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/lolApi/*"
  to = "http://ddragon.leagueoflegends.com/api/:splat"
  status = 200
  force = true
  