// eslint-disable-next-line @typescript-eslint/no-var-requires
const colors = require('tailwindcss/colors')

module.exports = {
  // purge: [],
  purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {},
    colors: {
      ...colors,
      'primary': 'var(--color-primary)',
      'primary-blur': 'var(--color-primary-blur)',
      'primary-accent': 'var(--color-primary-accent)',
      'secondary': 'var(--color-secondary)',
      'secondary-blur': 'var(--color-secondary-blur)',
      'secondary-accent': 'var(--color-secondary-accent)',
      'accent': 'var(--color-accent)',
      'accent-blur': 'var(--color-accent-blur)',
      'accent-accent': 'var(--color-accent-accent)',
      'error': 'var(--color-error)',
      'error-blur': 'var(--color-error-blur)',
      'error-accent': 'var(--color-error-accent)',
      'info': 'var(--color-info)',
      'info-blur': 'var(--color-info-blur)',
      'info-accent': 'var(--color-info-accent)',
      'success': 'var(--color-success)',
      'success-blur': 'var(--color-success-blur)',
      'success-accent': 'var(--color-success-accent)',
      'warning': 'var(--color-warning)',
      'warning-blur': 'var(--color-warning-blur)',
      'warning-accent': 'var(--color-warning-accent)',
      background: 'var(--color-background)',
      'background-accent':'var(--color-background-accent)',
      textPrimary: 'var(--color-textPrimary)',
      'blueGray': 'var(--color-blueGray)',
      'blueGray-blur': 'var(--color-blueGray-blur)',
      'blueGray-accent': 'var(--color-blueGray-accent)',

      'primary-100': 'var(--color-primary-100)',
      'primary-200': 'var(--color-primary-200)',
      'primary-300': 'var(--color-primary-300)',
      'primary-400': 'var(--color-primary-400)',
      'primary-500': 'var(--color-primary-500)',
      'primary-600': 'var(--color-primary-600)',
      'secondary-100': 'var(--color-secondary-100)',
      'secondary-200': 'var(--color-secondary-200)',
      'secondary-300': 'var(--color-secondary-300)',
      'secondary-400': 'var(--color-secondary-400)',
      'secondary-500': 'var(--color-secondary-500)',
      'secondary-600': 'var(--color-secondary-600)',
      'accent-100': 'var(--color-accent-100)',
      'accent-200': 'var(--color-accent-200)',
      'accent-300': 'var(--color-accent-300)',
      'accent-400': 'var(--color-accent-400)',
      'accent-500': 'var(--color-accent-500)',
      'accent-600': 'var(--color-accent-600)',
      'info-100': 'var(--color-info-100)',
      'info-200': 'var(--color-info-200)',
      'info-300': 'var(--color-info-300)',
      'info-400': 'var(--color-info-400)',
      'info-500': 'var(--color-info-500)',
      'info-600': 'var(--color-info-600)',
      'error-100': 'var(--color-error-100)',
      'error-200': 'var(--color-error-200)',
      'error-300': 'var(--color-error-300)',
      'error-400': 'var(--color-error-400)',
      'error-500': 'var(--color-error-500)',
      'error-600': 'var(--color-error-600)',
      'success-100': 'var(--color-success-100)',
      'success-200': 'var(--color-success-200)',
      'success-300': 'var(--color-success-300)',
      'success-400': 'var(--color-success-400)',
      'success-500': 'var(--color-success-500)',
      'success-600': 'var(--color-success-600)',
      'warning-100': 'var(--color-warning-100)',
      'warning-200': 'var(--color-warning-200)',
      'warning-300': 'var(--color-warning-300)',
      'warning-400': 'var(--color-warning-400)',
      'warning-500': 'var(--color-warning-500)',
      'warning-600': 'var(--color-warning-600)',
      'main': 'var(--color-main)',
      'app-bar': 'var(--color-app-bar)',
      'navigator': 'var(--color-navigator)',
      'sub-navigator': 'var(--color-sub-navigator)',
      'textPrimary-100': 'var(--color-textPrimary-100)',
      'textPrimary-200': 'var(--color-textPrimary-200)',
      'textPrimary-300': 'var(--color-textPrimary-300)',
      'textPrimary-400': 'var(--color-textPrimary-400)',
      'textPrimary-500': 'var(--color-textPrimary-500)',
      'textPrimary-600': 'var(--color-textPrimary-600)',

      'primary-dark-100': 'var(--color-dark-primary-100)',
      'primary-dark-200': 'var(--color-dark-primary-200)',
      'primary-dark-300': 'var(--color-dark-primary-300)',
      'primary-dark-400': 'var(--color-dark-primary-400)',
      'primary-dark-500': 'var(--color-dark-primary-500)',
      'primary-dark-600': 'var(--color-dark-primary-600)',
      'secondary-dark-100': 'var(--color-dark-secondary-100)',
      'secondary-dark-200': 'var(--color-dark-secondary-200)',
      'secondary-dark-300': 'var(--color-dark-secondary-300)',
      'secondary-dark-400': 'var(--color-dark-secondary-400)',
      'secondary-dark-500': 'var(--color-dark-secondary-500)',
      'secondary-dark-600': 'var(--color-dark-secondary-600)',
      'accent-dark-100': 'var(--color-dark-accent-100)',
      'accent-dark-200': 'var(--color-dark-accent-200)',
      'accent-dark-300': 'var(--color-dark-accent-300)',
      'accent-dark-400': 'var(--color-dark-accent-400)',
      'accent-dark-500': 'var(--color-dark-accent-500)',
      'accent-dark-600': 'var(--color-dark-accent-600)',
      'info-dark-100': 'var(--color-dark-info-100)',
      'info-dark-200': 'var(--color-dark-info-200)',
      'info-dark-300': 'var(--color-dark-info-300)',
      'info-dark-400': 'var(--color-dark-info-400)',
      'info-dark-500': 'var(--color-dark-info-500)',
      'info-dark-600': 'var(--color-dark-info-600)',
      'error-dark-100': 'var(--color-dark-error-100)',
      'error-dark-200': 'var(--color-dark-error-200)',
      'error-dark-300': 'var(--color-dark-error-300)',
      'error-dark-400': 'var(--color-dark-error-400)',
      'error-dark-500': 'var(--color-dark-error-500)',
      'error-dark-600': 'var(--color-dark-error-600)',
      'success-dark-100': 'var(--color-dark-success-100)',
      'success-dark-200': 'var(--color-dark-success-200)',
      'success-dark-300': 'var(--color-dark-success-300)',
      'success-dark-400': 'var(--color-dark-success-400)',
      'success-dark-500': 'var(--color-dark-success-500)',
      'success-dark-600': 'var(--color-dark-success-600)',
      'warning-dark-100': 'var(--color-dark-warning-100)',
      'warning-dark-200': 'var(--color-dark-warning-200)',
      'warning-dark-300': 'var(--color-dark-warning-300)',
      'warning-dark-400': 'var(--color-dark-warning-400)',
      'warning-dark-500': 'var(--color-dark-warning-500)',
      'warning-dark-600': 'var(--color-dark-warning-600)',
      'main-dark': 'var(--color-main-dark)',
      'app-bar-dark': 'var(--color-app-bar-dark)',
      'navigator-dark': 'var(--color-navigator-dark)',
      'sub-navigator-dark': 'var(--color-sub-navigator-dark)',
      'textPrimary-dark-100': 'var(--color-textPrimary-dark-100)',
      'textPrimary-dark-200': 'var(--color-textPrimary-dark-200)',
      'textPrimary-dark-300': 'var(--color-textPrimary-dark-300)',
      'textPrimary-dark-400': 'var(--color-textPrimary-dark-400)',
      'textPrimary-dark-500': 'var(--color-textPrimary-dark-500)',
      'textPrimary-dark-600': 'var(--color-textPrimary-dark-600)',
    },
    minWidth: {
      0: '0px',
      '1/4': '25%',
      '1/2': '50%',
      '3/4': '75%',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
